import requests
import json
from datetime import datetime
import time

class QdrantMonitor:
    def __init__(self):
        self.base_url = "http://localhost:6333"
        self.collection = "documents"
        self.current_user = "vincentspereira"
        self.current_time = "2025-05-21 02:19:15"
        
    def get_collection_stats(self) -> Dict:
        """Get collection statistics"""
        try:
            response = requests.get(
                f"{self.base_url}/collections/{self.collection}"
            )
            return response.json()
        except Exception as e:
            print(f"Error getting collection stats: {e}")
            return {}
            
    def get_collection_info(self) -> Dict:
        """Get detailed collection info"""
        try:
            response = requests.get(
                f"{self.base_url}/collections/{self.collection}/info"
            )
            return response.json()
        except Exception as e:
            print(f"Error getting collection info: {e}")
            return {}
            
    def generate_report(self):
        """Generate a monitoring report"""
        stats = self.get_collection_stats()
        info = self.get_collection_info()
        
        report = f"Qdrant Collection Monitoring Report\n"
        report += f"Generated by: {self.current_user}\n"
        report += f"Timestamp: {self.current_time}\n"
        report += "-" * 50 + "\n\n"
        
        if stats:
            report += "Collection Status:\n"
            report += f"Status: {stats.get('status', 'Unknown')}\n"
            report += f"Vector Size: {stats.get('config', {}).get('params', {}).get('vectors', {}).get('size', 0)}\n"
            
        if info:
            report += "\nCollection Info:\n"
            report += f"Total Vectors: {info.get('points_count', 0)}\n"
            report += f"Segments: {info.get('segments_count', 0)}\n"
            report += f"Vector Data Size: {info.get('vectors_size', 0)} bytes\n"
        
        return report

if __name__ == "__main__":
    monitor = QdrantMonitor()
    print(monitor.generate_report())