import requests
import json
from datetime import datetime
from typing import Dict, List

class RAGQueryTool:
    def __init__(self):
        self.api_url = "http://localhost:8000/query"
        self.qdrant_url = "http://localhost:6333"
        self.current_user = "vincentspereira"
        self.current_time = "2025-05-21 02:19:15"

    def search_documents(self, query: str, top_k: int = 5) -> List[Dict]:
        """Search documents with a query"""
        try:
            response = requests.post(
                self.api_url,
                json={"query": query, "top_k": top_k}
            )
            return response.json()
        except Exception as e:
            print(f"Error querying documents: {e}")
            return []

    def format_results(self, results: List[Dict]) -> str:
        """Format search results for display"""
        output = f"Query Results (Generated by {self.current_user} at {self.current_time}):\n\n"
        
        for i, result in enumerate(results, 1):
            output += f"Result {i}:\n"
            output += f"Source: {result.get('metadata', {}).get('source', 'Unknown')}\n"
            output += f"Relevance Score: {result.get('score', 0):.4f}\n"
            output += "Content:\n"
            output += f"{result.get('text', 'No content available')}\n"
            output += "-" * 80 + "\n\n"
            
        return output

if __name__ == "__main__":
    rag_tool = RAGQueryTool()
    
    print("RAG Query Tool")
    print("Enter 'quit' to exit")
    print("-" * 50)
    
    while True:
        query = input("\nEnter your query: ").strip()
        if query.lower() == 'quit':
            break
            
        top_k = input("Number of results (default 5): ").strip()
        top_k = int(top_k) if top_k.isdigit() else 5
        
        results = rag_tool.search_documents(query, top_k)
        print("\n" + rag_tool.format_results(results))